// Accounts
export const SET_ACCOUNT = 'SET_ACCOUNT';
export const SET_ACCOUNTS = 'SET_ACCOUNTS';
export const SET_ACCOUNT_BALANCE = 'SET_ACCOUNT_BALANCE';
export const SET_SELECTED_ACCOUNT = 'SET_SELECTED_ACCOUNT';
export const SET_ACCOUNT_TOKENS = 'SET_ACCOUNT_TOKENS';

// Tokens
export const SET_ALL_TOKENS = 'SET_ALL_TOKENS';

// Signers
export const SET_SIGNERS_ACTION = 'SET_SIGNERS_ACTION';
export const SET_SIGNERS_LOADING = 'SET_SIGNERS_LOADING';
export const SELECT_SIGNER_ACTION = 'SELECT_SIGNER_ACTION';
export const SET_SIGNER_TOKENS_ACTION = 'SELECT_SIGNER_TOKENS_ACTION';
export const SET_SIGNER_BALANCE_ACTION = 'SELECT_SIGNER_BALANCE_ACTION';

// Tokens
export const RELOAD_TOKENS_APPROVED = 'RELOAD_TOKENS';
export const SET_TOKENS_APPROVED_ACTION = 'SET_TOKENS_AVAILABLE_ACTION';
export const SET_TOKENS_SELECTED_SIGNER_ACTION = 'SET_TOKENS_SIGNER_BALANCE_ACTION';
export const SET_TOKENS_SELECTED_SIGNER_LOADING = 'SET_TOKENS_SIGNER_BALANCE_LOADING';
export const SET_TOKENS_APPROVED_LOADING = 'SET_TOKENS_LOADING';

// Pools
export const RELOAD_POOLS = 'RELOAD_POOLS';
export const SET_POOLS_ACTION = 'SET_POOLS_ACTION';
export const SET_POOLS_LOADING = 'SET_POOLS_LOADING';
