// Signers
export const SET_SIGNERS_ACTION = 'SET_SIGNERS_ACTION';
export const SET_SIGNERS_LOADING = 'SET_SIGNERS_LOADING';
export const SELECT_SIGNER_ACTION = 'SELECT_SIGNER_ACTION';

// Tokens
export const RELOAD_TOKENS = 'RELOAD_TOKENS';
export const SET_TOKENS_ACTION = 'SET_TOKENS_ACTION';
export const SET_TOKENS_LOADING = 'SET_TOKENS_LOADING';

// Pools
export const RELOAD_POOLS = 'RELOAD_POOLS';
export const SET_POOLS_ACTION = 'SET_POOLS_ACTION';
export const SET_POOLS_LOADING = 'SET_POOLS_LOADING';
