// Signers
export const SET_SIGNERS_ACTION = "SET_SIGNERS_ACTION";
export const SELECT_SIGNER_ACTION = "SELECT_SIGNER_ACTION";

// Tokens
export const SET_TOKENS_ACTION = "SET_TOKENS_ACTION";

// Pools
export const SET_POOLS_ACTION = "SET_POOLS_ACTION";